config/routes.rb
Rails.application.routes.draw do
  resources :game_players
  resources :player_moves
  resources :players

  root 'games#play'
  
  get 'games/index' => 'games#index'
  get 'games/play' => 'games#play'
  
  post 'games/start' => 'games#start'
  post 'games/stop' => 'games#stop'
  post 'games/winner' => 'games#winner'
  post 'games/ping' => 'games#ping'
  post 'games/move' => 'games#move'
  post 'games/join' => 'games#join'
  

end

app/models/game.rb
class Game < ActiveRecord::Base
    has_many :game_players
    has_many :players, through: :game_players
    belongs_to :current_active_player, class_name: :Player, validate: true
    belongs_to :winner, class_name: :Player, validate: true
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, 
    :edit, 
    :update, 
    :destroy
  ]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end
  
  # POST /games/play
  def stop
    p = params[:player]
    player = Player.find_by_username_and_password p[:username], 
      p[:password]
    game = Game.find_by_room params[:room]
    game.status = 'Closed'
    game.winner = player
    game.save
    render json: {game: game, winner: player}
  end
  
  # POST /games/winner
  def winner
    game = Game.find_by_room params[:room]
    player_id = game.winner
    player = Player.find player_id
    render json: {game: game, winner: player}
  end
  
  # GET /games/play
  def play
    @open_games = Game.where status: 'Open'
    render file: 'games/play'
  end
  
  def move
    game = Game.find_by_room params[:room]
    game.status = 'Player Moved'
    
    nap =  params[:next_active_player]
    nextPlayer = Player.find_by_username_and_password nap[:username],
      nap[:password]
    game.current_active_player = nextPlayer
    game.save
    
    p = params[:owner]
    username = p[:username]
    password = p[:password]
    disk_index = params[:disk_index]
    player = Player.find_by_username_and_password username, 
      password
    
    game_player = GamePlayer.find_by game: game, player: player
    player_move = PlayerMove.create game_player: game_player, 
      index: disk_index
    
    o = 
    {
      game: game,
      player_move: player_move, 
      latest_move_owner: player
    }
    render json: o
  end
  
  # POST /games/start
  def start
    p = params[:player]
    player = Player.find_or_create_by username: p[:username], 
      password: p[:password]
    player.disk_color = p[:disk_color]
    player.index = p[:index]
    player.save
    
    game = Game.create room: params[:room]
    game.players << player
    #game_player = GamePlayer.create game: game, player: player
    game_player = GamePlayer.find_by game: game, player: player
    
    o = {
      game: game, 
      game_player: game_player, 
      players: game.players
    }
    render json: o
  end
  
  #TODO: Refactor using start().
  # POST /games/join
  def join
    p = params[:player]
    player = Player.find_or_create_by username: p[:username], 
      password: p[:password],
      disk_color: p[:disk_color],
      index: p[:index]
    
    game = Game.find_by_room params[:room]
    game.status = 'Started'
    game.players << player
    game.save
    
    render json: to_json(params[:room])
  end
  
  # POST /games/ping
  def ping
    render json: to_json(params[:room])
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      #TODO: Check :resource in routes.
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:room, :game_type, :status, :row, :column)
    end
    
    def to_json room
      game = Game.find_by_room room
      #TODO: Refactor.
      sql = "SELECT pm.* FROM player_moves pm 
        INNER JOIN game_players gp ON gp.id = pm.game_player_id 
        INNER JOIN games g ON gp.game_id = g.id 
        WHERE g.id = ? 
        ORDER BY pm.id DESC LIMIT 1"
      player_move = PlayerMove.find_by_sql([sql, game.id])[0]
      if player_move.nil?
        latest_move_owner = []
        disk_color = []
      else
        latest_move_owner = GamePlayer.find player_move.game_player_id
        disk_color = latest_move_owner.player.disk_color
      end
      #/TODO: Refactor.
      {
        game: game, 
        players: game.players, 
        latest_move_owner: latest_move_owner,
        latest_move: player_move,
        disk_color: disk_color
      }
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room %><br>
    <%= f.text_field :room %>
  </div>
  <div class="field">
    <%= f.label :game_type %><br>
    <%= f.text_field :game_type %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :row %><br>
    <%= f.number_field :row %>
  </div>
  <div class="field">
    <%= f.label :column %><br>
    <%= f.number_field :column %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Room</th>
      <th>Game type</th>
      <th>Status</th>
      <th>Row</th>
      <th>Column</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.room %></td>
        <td><%= game.game_type %></td>
        <td><%= game.status %></td>
        <td><%= game.row %></td>
        <td><%= game.column %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/play.html.erb
<div id="game" class="play">
  <input type="hidden"
        id="states"
        data-local-player-index=""
        data-join-room="" />
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 id="room" class="panel-title">
        Game Room:
        <span></span>
      </h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-12 col-md-4">
          
          <div class="panel panel-default">
            <div class="panel-body">
              <nav>
                <div class="form-group">
                  <label for="username">Enter Desired Username:</label>
                  <input type="text" 
                    class="form-control" 
                    id="username" 
                    value="Player 1" />
                </div>
                <div class="form-group">
                  <label for="password">Enter Password:</label>
                  <input type="password" 
                    class="form-control" 
                    id="password"
                    value="x" />
                </div>
                <div class="form-group">
                  <label for="game-type">Select Game Type:</label>
                  <select class="form-control" id="game-type">
                    <option>Player VS. Player</option>
                    <option>Player VS. AI</option>
                  </select>
                </div>
                <div class="form-group">
                  <label for="game-type">Select Open Games:</label>
                  <% 
                    open_games = ['Select one']
                    open_games += @open_games.map {|g| [g.room, g.room]} 
                  %>
                  <%= 
                    select_tag(
                      :room, 
                      options_for_select(open_games),
                      {
                        class: 'form-control', 
                        id: 'open-games'
                      }
                    )
                  %>
                </div>
                <div class="form-group">
                  <button id="play-game" 
                    class="form-control btn btn-primary">
                    Play
                  </button>
                </div>
              </nav>
              <div id="current-player" class="form-group">
                <label>Current Active Player:</label>
                <div>No Player</div>
              </div>
            </div>
          </div>
          
        </div>
  
        <div class="col-sm-12 col-md-8">
          <div class="panel panel-default">
            <div class="board-container panel-body">
              <div id="board"></div>
            </div>
          </div>
        </div>
  
      </div>
  
    </div>
  </div>
  
  <!-- Modals. -->
  <div id="waiting-opponent-modal"
    class="modal fade"
    role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Game Status</h4>
        </div>
        <div class="modal-body">
          <p>
            Waiting for an opponent for room <span></span>.
          </p>
        </div>
        <div class="modal-footer">
          <a href="#"
            class="cancel-game btn btn-default"
            data-dismiss="modal">Cancel</a>
        </div>
      </div>
    </div>
  </div>
  
  <div id="winner-modal"
    class="modal fade"
    role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button"
            class="close"
            data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Game Over</h4>
        </div>
        <div class="modal-body">
          <p>
            The winner is <span></span>
          </p>
        </div>
        <div class="modal-footer">
          <button type="button"
            class="btn btn-default"
            data-dismiss="modal">I'm cool with that!</button>
        </div>
      </div>
    </div>
  </div>
  <!-- /Modals. -->
</div>

app/views/games/rooms.html.erb
<div id="game" class="rooms">
  <h1>Game Rooms</h1>
  <% if !@games.blank? %>
  
    <div>
      <div class="form-group">
        <label for="full-name">Enter Desired Username:</label>
        <input type="text" 
          class="form-control" 
          id="username" 
          value="Player 2" />
      </div>
      <div class="form-group">
        <label for="full-name">Enter Password:</label>
        <input type="password" 
          class="form-control" 
          id="password"
          value="y" />
      </div>
    </div>
  
    <ul class="list-group">
      <% 
        @games.each do |g| 
        r = g.room
      %>
        <li class="list-group-item">
          Game Room: <%= r %>
          <%= 
            link_to 'Join', 
              {action: :play_room}, 
              room: r,
              'data-room': r,
              class: 'join-game' 
          %>
        </li>
      <% end %>
    </ul>
  <% else %>
    No Game Rooms listed.
    <%= link_to 'Create one', root_path %>
  <% end %>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @game.room %>
</p>

<p>
  <strong>Game type:</strong>
  <%= @game.game_type %>
</p>

<p>
  <strong>Status:</strong>
  <%= @game.status %>
</p>

<p>
  <strong>Row:</strong>
  <%= @game.row %>
</p>

<p>
  <strong>Column:</strong>
  <%= @game.column %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>