config/routes.rb
Rails.application.routes.draw do
  resources :game_players
  resources :player_moves
  resources :players

  root 'games#play'
  
  get 'games/index' => 'games#index'
  get 'games/play' => 'games#play'
  
  post 'games/start' => 'games#start'
  post 'games/stop' => 'games#stop'
  post 'games/winner' => 'games#winner'
  post 'games/ping' => 'games#ping'
  post 'games/move' => 'games#move'
  post 'games/join' => 'games#join'
  

end

app/models/game_player.rb
class GamePlayer < ActiveRecord::Base
    belongs_to :game
    belongs_to :player
    
    has_many :player_moves
end

app/controllers/game_players_controller.rb
class GamePlayersController < ApplicationController
  before_action :set_game_player, only: [:show, :edit, :update, :destroy]

  # GET /game_players
  # GET /game_players.json
  def index
    @game_players = GamePlayer.all
  end

  # GET /game_players/1
  # GET /game_players/1.json
  def show
  end

  # GET /game_players/new
  def new
    @game_player = GamePlayer.new
  end

  # GET /game_players/1/edit
  def edit
  end

  # POST /game_players
  # POST /game_players.json
  def create
    @game_player = GamePlayer.new(game_player_params)

    respond_to do |format|
      if @game_player.save
        format.html { redirect_to @game_player, notice: 'Game player was successfully created.' }
        format.json { render :show, status: :created, location: @game_player }
      else
        format.html { render :new }
        format.json { render json: @game_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_players/1
  # PATCH/PUT /game_players/1.json
  def update
    respond_to do |format|
      if @game_player.update(game_player_params)
        format.html { redirect_to @game_player, notice: 'Game player was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_player }
      else
        format.html { render :edit }
        format.json { render json: @game_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_players/1
  # DELETE /game_players/1.json
  def destroy
    @game_player.destroy
    respond_to do |format|
      format.html { redirect_to game_players_url, notice: 'Game player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_player
      @game_player = GamePlayer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_player_params
      params.fetch(:game_player, {})
    end
end

app/helpers/game_players_helper.rb
module GamePlayersHelper
end

app/views/game_players/_form.html.erb
<%= form_for(@game_player) do |f| %>
  <% if @game_player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_player.errors.count, "error") %> prohibited this game_player from being saved:</h2>

      <ul>
      <% @game_player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_players/edit.html.erb
<h1>Editing Game Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_player %> |
<%= link_to 'Back', game_players_path %>

app/views/game_players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Game Players</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_players.each do |game_player| %>
      <tr>
        <td><%= link_to 'Show', game_player %></td>
        <td><%= link_to 'Edit', edit_game_player_path(game_player) %></td>
        <td><%= link_to 'Destroy', game_player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game player', new_game_player_path %>

app/views/game_players/new.html.erb
<h1>New Game Player</h1>

<%= render 'form' %>

<%= link_to 'Back', game_players_path %>

app/views/game_players/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_game_player_path(@game_player) %> |
<%= link_to 'Back', game_players_path %>