config/routes.rb
Rails.application.routes.draw do
  resources :game_players
  resources :player_moves
  resources :players

  root 'games#play'
  
  get 'games/index' => 'games#index'
  get 'games/play' => 'games#play'
  
  post 'games/start' => 'games#start'
  post 'games/stop' => 'games#stop'
  post 'games/winner' => 'games#winner'
  post 'games/ping' => 'games#ping'
  post 'games/move' => 'games#move'
  post 'games/join' => 'games#join'
  

end

app/models/player.rb
class Player < ActiveRecord::Base
    has_many :game_players
    has_many :games, through: :game_players
    has_many :player_moves, through: :game_players
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:username, :password, :disk_color)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :disk_color %><br>
    <%= f.text_field :disk_color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Disk color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.username %></td>
        <td><%= player.password %></td>
        <td><%= player.disk_color %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @player.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @player.password %>
</p>

<p>
  <strong>Disk color:</strong>
  <%= @player.disk_color %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>