config/routes.rb
Rails.application.routes.draw do
  resources :game_players
  resources :player_moves
  resources :players

  root 'games#play'
  
  get 'games/index' => 'games#index'
  get 'games/play' => 'games#play'
  
  post 'games/start' => 'games#start'
  post 'games/stop' => 'games#stop'
  post 'games/winner' => 'games#winner'
  post 'games/ping' => 'games#ping'
  post 'games/move' => 'games#move'
  post 'games/join' => 'games#join'
  

end

app/models/player_move.rb
class PlayerMove < ActiveRecord::Base
    belongs_to :game_player
end

app/controllers/player_moves_controller.rb
class PlayerMovesController < ApplicationController
  before_action :set_player_move, only: [:show, :edit, :update, :destroy]

  # GET /player_moves
  # GET /player_moves.json
  def index
    @player_moves = PlayerMove.all
  end

  # GET /player_moves/1
  # GET /player_moves/1.json
  def show
  end

  # GET /player_moves/new
  def new
    @player_move = PlayerMove.new
  end

  # GET /player_moves/1/edit
  def edit
  end

  # POST /player_moves
  # POST /player_moves.json
  def create
    @player_move = PlayerMove.new(player_move_params)

    respond_to do |format|
      if @player_move.save
        format.html { redirect_to @player_move, notice: 'Player move was successfully created.' }
        format.json { render :show, status: :created, location: @player_move }
      else
        format.html { render :new }
        format.json { render json: @player_move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_moves/1
  # PATCH/PUT /player_moves/1.json
  def update
    respond_to do |format|
      if @player_move.update(player_move_params)
        format.html { redirect_to @player_move, notice: 'Player move was successfully updated.' }
        format.json { render :show, status: :ok, location: @player_move }
      else
        format.html { render :edit }
        format.json { render json: @player_move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_moves/1
  # DELETE /player_moves/1.json
  def destroy
    @player_move.destroy
    respond_to do |format|
      format.html { redirect_to player_moves_url, notice: 'Player move was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_move
      @player_move = PlayerMove.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_move_params
      params.require(:player_move).permit(:index)
    end
end

app/helpers/player_moves_helper.rb
module PlayerMovesHelper
end

app/views/player_moves/_form.html.erb
<%= form_for(@player_move) do |f| %>
  <% if @player_move.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player_move.errors.count, "error") %> prohibited this player_move from being saved:</h2>

      <ul>
      <% @player_move.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :index %><br>
    <%= f.number_field :index %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/player_moves/edit.html.erb
<h1>Editing Player Move</h1>

<%= render 'form' %>

<%= link_to 'Show', @player_move %> |
<%= link_to 'Back', player_moves_path %>

app/views/player_moves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Player Moves</h1>

<table>
  <thead>
    <tr>
      <th>Index</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @player_moves.each do |player_move| %>
      <tr>
        <td><%= player_move.index %></td>
        <td><%= link_to 'Show', player_move %></td>
        <td><%= link_to 'Edit', edit_player_move_path(player_move) %></td>
        <td><%= link_to 'Destroy', player_move, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player move', new_player_move_path %>

app/views/player_moves/new.html.erb
<h1>New Player Move</h1>

<%= render 'form' %>

<%= link_to 'Back', player_moves_path %>

app/views/player_moves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @player_move.index %>
</p>

<%= link_to 'Edit', edit_player_move_path(@player_move) %> |
<%= link_to 'Back', player_moves_path %>